name: reusable workflow - execute unit tests, build image, deploy to ecr and update ecs service

on:
  workflow_call:
    inputs:
      microservice:
        required: true
        type: string
      microservice-path:
        required: true
        type: string
        
jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
            - '${{ inputs.microservice-path }}/**'

  unit-test:
    name: unit tests
    # needs: changes
    # if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      working-directory: ${{ inputs.microservice-path }} 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      working-directory: ${{ inputs.microservice-path }} 
      run: |
        pip install pytest pytest-cov
        pytest --cov=. -v -s --cov-fail-under=80
